name: tset
favicon: null
layout_spectrum: 0.6723390012048185
typography_spectrum: 0.19265327043831348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5240604765713215
  lightness: 0.635761795565486
  saturation: 0.850935292430222
  rhythmicContrast: 0.2919070415664464
purpose: []
